### ISSUE TITLE
How to run the code

### ISSUE THREAD

**Issue by bkzfyx** [fidler-lab/social-driving#1]
I have installed sdriving, could anyone please tell me how to run the code?

**Comment by avik-pal** [comment]
@bkzfyx https://avikpal.gitbook.io/social-driving/environments/example shows how to use the package.

**Comment by bkzfyx** [comment]
> @bkzfyx https://avikpal.gitbook.io/social-driving/environments/example shows how to use the package.

Thank you very much, I am sorry for my negligence.
